version: '3.8'

services:
  dl-solutions-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: dl-solutions-nextjs
    networks:
      - dl-solutions-network

networks:
  dl-solutions-network:
    driver: bridge 