[build]
  command = "pnpm build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.20.0"
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirections pour Next.js App Router
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.clerk.com https://*.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: https://*.unsplash.com; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://*.netlify.com https://*.vercel.com https://*.supabase.com https://*.clerk.com https://*.stripe.com https://*.openai.com https://*.elevenlabs.io;"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://votre-domaine.netlify.app"
  NEXT_PUBLIC_API_URL = "https://votre-backend-api.vercel.app"

[context.branch-deploy.environment]
  NODE_ENV = "staging"
  NEXT_PUBLIC_APP_URL = "https://staging.votre-domaine.netlify.app"
  NEXT_PUBLIC_API_URL = "https://votre-backend-api.vercel.app"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  NEXT_PUBLIC_APP_URL = "https://preview.votre-domaine.netlify.app"
  NEXT_PUBLIC_API_URL = "https://votre-backend-api.vercel.app"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.processing.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ] 