# Configuration Netlify pour DAVY Trading Platform
# Version: 3.2 - Configuration SSR pour Next.js

[build]
  # Commande de build avec npm
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  # Ignore linting errors in production
  ESLINT_NO_DEV_ERRORS = "true"
  # Optimisation des variables d'environnement
  NETLIFY_FUNCTIONS_TIMEOUT = "10"
  NETLIFY_FUNCTIONS_MAX_SIZE = "50"
  # Variables essentielles seulement pour les fonctions
  NEXT_PUBLIC_APP_URL = "https://daveandlucesolutions.com"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = true

# Configuration des fonctions Netlify
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Redirections pour les fonctions Netlify
[[redirects]]
  from = "/api/scraping/*"
  to = "/.netlify/functions/scraping-api/:splat"
  status = 200

[[redirects]]
  from = "/api/debug/*"
  to = "/.netlify/functions/scraping-api/:splat"
  status = 200

[[redirects]]
  from = "/api/trading/*"
  to = "/.netlify/functions/trading-api/:splat"
  status = 200

# Configuration du domaine personnalisé
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirection HTTPS
[[redirects]]
  from = "http://daveandlucesolutions.com/*"
  to = "https://daveandlucesolutions.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.daveandlucesolutions.com/*"
  to = "https://www.daveandlucesolutions.com/:splat"
  status = 301
  force = true 