[build]
  command = "pnpm run build && pnpm run export"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NODE_ENV = "production"

[dev]
  command = "pnpm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = true

# Configuration des fonctions Netlify désactivée temporairement
# [functions]
#   directory = "netlify/functions"
#   node_bundler = "esbuild"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Redirections pour les fonctions Netlify désactivées temporairement
# [[redirects]]
#   from = "/api/test"
#   to = "/.netlify/functions/hello"
#   status = 200

# [[redirects]]
#   from = "/api/hello"
#   to = "/.netlify/functions/hello"
#   status = 200

# [[redirects]]
#   from = "/api/trading/*"
#   to = "/.netlify/functions/trading-api/:splat"
#   status = 200 