[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"
  node_version = "18.20.0"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_SHARP_PATH = "/opt/buildhome/.npm-global/lib/node_modules/sharp"
  NEXT_OPTIMIZE_CSS = "true"
  NEXT_OPTIMIZE_CSS_INLINE_THRESHOLD = "8192"
  NEXT_OPTIMIZE_CSS_PRELOAD_FONTS = "true"
  YARN_FLAGS = "--network-timeout 100000"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.processing.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ] 