import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://dlsolutionssarl.tech'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/portfolio',
          '/portfolio/batobaye',
          '/services',
          '/a-propos',
          '/contact',
          '/dl-style',
          '/novaworld',
          '/novacore',
          '/novacore/pricing',
          '/marketing-digital',
          '/e-commerce',
          '/formations',
          '/capacites-techniques',
          '/devis',
          '/rendez-vous',
          '/solutions',
          '/solutions/immobilier',
          '/solutions/hospitalier',
          '/solutions/banque',
          '/solutions/assurance',
          '/nova-ia',
          '/sentinel-zero',
          '/quantum-intelligence',
          '/trading',
          '/trading-charts',
          '/drones',
          '/dl-transport',
          '/dl-immobilier'
        ],
        disallow: [
          '/admin',
          '/api/',
          '/_next/',
          '/private/',
          '/temp/',
          '/novacore/checkout',
          '/sign-in',
          '/sign-up',
          '/dashboard',
          '/intranet',
          '/.env',
          '/.git',
          '/node_modules',
          '/package.json',
          '/package-lock.json',
          '/yarn.lock',
          '/.next',
          '/out',
          '/dist',
          '/build'
        ]
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/portfolio',
          '/portfolio/batobaye',
          '/services',
          '/a-propos',
          '/contact',
          '/dl-style',
          '/novaworld',
          '/novacore',
          '/novacore/pricing',
          '/marketing-digital',
          '/e-commerce',
          '/formations',
          '/capacites-techniques',
          '/devis',
          '/rendez-vous',
          '/solutions',
          '/solutions/immobilier',
          '/solutions/hospitalier',
          '/solutions/banque',
          '/solutions/assurance',
          '/nova-ia',
          '/sentinel-zero',
          '/quantum-intelligence',
          '/trading',
          '/trading-charts',
          '/drones',
          '/dl-transport',
          '/dl-immobilier'
        ],
        disallow: [
          '/admin',
          '/api/',
          '/_next/',
          '/private/',
          '/temp/',
          '/novacore/checkout',
          '/sign-in',
          '/sign-up',
          '/dashboard',
          '/intranet',
          '/.env',
          '/.git',
          '/node_modules',
          '/package.json',
          '/package-lock.json',
          '/yarn.lock',
          '/.next',
          '/out',
          '/dist',
          '/build'
        ],
        crawlDelay: 1
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/portfolio',
          '/portfolio/batobaye',
          '/services',
          '/a-propos',
          '/contact',
          '/dl-style',
          '/novaworld',
          '/novacore',
          '/novacore/pricing',
          '/marketing-digital',
          '/e-commerce',
          '/formations',
          '/capacites-techniques',
          '/devis',
          '/rendez-vous',
          '/solutions',
          '/solutions/immobilier',
          '/solutions/hospitalier',
          '/solutions/banque',
          '/solutions/assurance',
          '/nova-ia',
          '/sentinel-zero',
          '/quantum-intelligence',
          '/trading',
          '/trading-charts',
          '/drones',
          '/dl-transport',
          '/dl-immobilier'
        ],
        disallow: [
          '/admin',
          '/api/',
          '/_next/',
          '/private/',
          '/temp/',
          '/novacore/checkout',
          '/sign-in',
          '/sign-up',
          '/dashboard',
          '/intranet',
          '/.env',
          '/.git',
          '/node_modules',
          '/package.json',
          '/package-lock.json',
          '/yarn.lock',
          '/.next',
          '/out',
          '/dist',
          '/build'
        ],
        crawlDelay: 1
      },
      {
        userAgent: 'Yandex',
        allow: [
          '/',
          '/portfolio',
          '/portfolio/batobaye',
          '/services',
          '/a-propos',
          '/contact',
          '/dl-style',
          '/novaworld',
          '/novacore',
          '/novacore/pricing',
          '/marketing-digital',
          '/e-commerce',
          '/formations',
          '/capacites-techniques',
          '/devis',
          '/rendez-vous',
          '/solutions',
          '/solutions/immobilier',
          '/solutions/hospitalier',
          '/solutions/banque',
          '/solutions/assurance',
          '/nova-ia',
          '/sentinel-zero',
          '/quantum-intelligence',
          '/trading',
          '/trading-charts',
          '/drones',
          '/dl-transport',
          '/dl-immobilier'
        ],
        disallow: [
          '/admin',
          '/api/',
          '/_next/',
          '/private/',
          '/temp/',
          '/novacore/checkout',
          '/sign-in',
          '/sign-up',
          '/dashboard',
          '/intranet',
          '/.env',
          '/.git',
          '/node_modules',
          '/package.json',
          '/package-lock.json',
          '/yarn.lock',
          '/.next',
          '/out',
          '/dist',
          '/build'
        ],
        crawlDelay: 2
      }
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl
  }
} 